mail: Handle unexpected Content-Type
Some mail clients set wrong content-type for PDF attachments.

Content-Type: bin/plain; charset="ISO 8859-1"
Content-Disposition: attachment; filename="filename.pdf"
Content-Transfer-Encoding: base64

In this case, receiving unexpected type like bin/plain instead of Application/pdf
leads to Python content manager error:

File "/usr/lib/python3.9/email/contentmanager.py", line 25, in get_content
    raise KeyError(content_type)
KeyError: 'bin/plain'

This makes odoo impossible to parse such message, even if pdf attachment is not broken.